%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 8.5 and Fixed-Point Designer 5.0           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [y_out,delayed_xout] = filter1d_wrapper_fixpt(x_in,h_in1,h_in2,h_in3,h_in4)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128 );
    x_in_in = fi( x_in, 1, 32, 30, fm );
    h_in1_in = fi( h_in1, 1, 32, 33, fm );
    h_in2_in = fi( h_in2, 1, 32, 34, fm );
    h_in3_in = fi( h_in3, 0, 32, 34, fm );
    h_in4_in = fi( h_in4, 0, 32, 33, fm );
    [y_out_out,delayed_xout_out] = filter1d_fixpt( x_in_in, h_in1_in, h_in2_in, h_in3_in, h_in4_in );
    y_out = double( y_out_out );
    delayed_xout = double( delayed_xout_out );
end
